
logging:
  config: classpath:log4j2-spring.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.70.228.230:3306/control_strategy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: '@Wy12345'
  application:
    name: controlstrategy
  redis:
    host: 127.0.0.1
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.fsy.controlstrategy.entity
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

controlstrategy:
  jwt:
    # 加密密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长
    expire: 604800
    # header 名称
    header: token